In [1]:
import pandas as pd

# Woking with JSON

In [4]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [16]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,api_url,api_docs,api_terms,base,date,time_last_updated,rates
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.050110
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,1.051777
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,1.426475
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,7.270000
ANG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.024424
...,...,...,...,...,...,...,...
XOF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,7.637893
XPF,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,1.389489
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,3.411028
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.204121
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2021-03-31,1617148801,0.301281

In [5]:
import sys
!{sys.executable} -m pip install requests

Requirement already satisfied: requests in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (2.34.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests) (3.15)
Requirement already satisfied: urllib3<3,>=1.26 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in c:\users\hp\appdata\local\programs\python\python311\lib\site-packages (from requests) (2026.4.22)

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

# Working with SQL

In [11]:
import sys
!{sys.executable} -m pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.7.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp311-cp311-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB 435.7 kB/s eta 0:00:41
   ---------------------------------------- 0.2/17.7 MB 1.5 MB/s eta 0:00:12
    --------------------------------------- 0.4/17.7 MB 2.6 MB/s eta 0:00:07
   - -------------------------------------- 0.7/17.7 MB 3.4 MB/s eta 0:00:05
   - -------------------------------------- 0.9/17.7 MB 3.7 MB/s eta 0:00:05
   -- ------------------------------------- 1.2/17.7 MB 4.1 MB/s eta 0:00:05
   --- ------------------------------------ 1.4/17.7 MB 4.3 MB/s eta 0:00:04
   --- ------------------------------------ 1.7/17.7 MB 4.3 MB/s eta 0:00:04
   ---- ----------------------------------- 2.0/17.7 MB 4.7 MB/s eta 0:00:04
   ----- ---------------------------------- 2.3/17.7 MB 4.8 MB/s eta 0:00:04
   ----- ---------------------------------- 2.5/17.7 MB 4.8 MB/s eta 0:00:04
   ------ --------------------------------- 2.8/17.7 MB 4.9 MB/s eta 0:00:04
   ------ --------------------------------- 3.0/17.7 MB 4.7 MB/s eta 0:00:04
   ------ --------------------------------- 3.1/17.7 MB 4.6 MB/s eta 0:00:04
   ------- -------------------------------- 3.2/17.7 MB 4.6 MB/s eta 0:00:04
   ------- -------------------------------- 3.5/17.7 MB 4.7 MB/s eta 0:00:04
   -------- ------------------------------- 3.7/17.7 MB 4.6 MB/s eta 0:00:04
   -------- ------------------------------- 3.9/17.7 MB 4.7 MB/s eta 0:00:03
   --------- ------------------------------ 4.1/17.7 MB 4.6 MB/s eta 0:00:03
   --------- ------------------------------ 4.3/17.7 MB 4.7 MB/s eta 0:00:03
   ---------- ----------------------------- 4.5/17.7 MB 4.6 MB/s eta 0:00:03
   ---------- ----------------------------- 4.8/17.7 MB 4.6 MB/s eta 0:00:03
   ----------- ---------------------------- 5.0/17.7 MB 4.6 MB/s eta 0:00:03
   ----------- ---------------------------- 5.3/17.7 MB 4.7 MB/s eta 0:00:03
   ------------ --------------------------- 5.4/17.7 MB 4.6 MB/s eta 0:00:03
   ------------ --------------------------- 5.7/17.7 MB 4.6 MB/s eta 0:00:03
   ------------- -------------------------- 5.9/17.7 MB 4.7 MB/s eta 0:00:03
   -------------- ------------------------- 6.2/17.7 MB 4.7 MB/s eta 0:00:03
   -------------- ------------------------- 6.5/17.7 MB 4.7 MB/s eta 0:00:03
   --------------- ------------------------ 6.7/17.7 MB 4.7 MB/s eta 0:00:03
   --------------- ------------------------ 6.9/17.7 MB 4.7 MB/s eta 0:00:03
   ---------------- ----------------------- 7.2/17.7 MB 4.8 MB/s eta 0:00:03
   ---------------- ----------------------- 7.4/17.7 MB 4.8 MB/s eta 0:00:03
   ----------------- ---------------------- 7.6/17.7 MB 4.8 MB/s eta 0:00:03
   ----------------- ---------------------- 7.9/17.7 MB 4.8 MB/s eta 0:00:03
   ------------------ --------------------- 8.1/17.7 MB 4.8 MB/s eta 0:00:03
   ------------------ --------------------- 8.3/17.7 MB 4.8 MB/s eta 0:00:02
   ------------------- -------------------- 8.6/17.7 MB 4.8 MB/s eta 0:00:02
   -------------------- ------------------- 8.9/17.7 MB 4.9 MB/s eta 0:00:02
   -------------------- ------------------- 9.1/17.7 MB 4.8 MB/s eta 0:00:02
   --------------------- ------------------ 9.4/17.7 MB 4.8 MB/s eta 0:00:02
   --------------------- ------------------ 9.6/17.7 MB 4.9 MB/s eta 0:00:02
   ---------------------- ----------------- 9.9/17.7 MB 4.9 MB/s eta 0:00:02
   ---------------------- ----------------- 10.0/17.7 MB 4.9 MB/s eta 0:00:02
   ----------------------- ---------------- 10.2/17.7 MB 4.9 MB/s eta 0:00:02
   ----------------------- ---------------- 10.5/17.7 MB 5.0 MB/s eta 0:00:02
   ------------------------ --------------- 10.6/17.7 MB 5.0 MB/s eta 0:00:02
   ------------------------ --------------- 10.9/17.7 MB 5.0 MB/s eta 0:00:02
   ------------------------ --------------- 11.0/17.7 MB 5.0 MB/s eta 0:00:02
   ------------------------- -------------- 11.3/17.7 MB 5.0 MB/s eta 0:00:02
   -------------------------- ------------- 11.5/17.7 MB 5.0 MB/s eta 0:00:02
   -------------------------- ------------- 11.8/17.7 MB 5.0 MB/s eta 0:00:02
   --------------------------- ------------ 12.0/17.7 MB 5.0 MB/s eta 0:00:02
   --------------------------- ------------ 12.2/17.7 MB 4.9 MB/s eta 0:00:02
   ---------------------------- ----------- 12.4/17.7 MB 4.9 MB/s eta 0:00:02
   ---------------------------- ----------- 12.7/17.7 MB 4.9 MB/s eta 0:00:02
   ----------------------------- ---------- 13.0/17.7 MB 4.8 MB/s eta 0:00:01
   ----------------------------- ---------- 13.2/17.7 MB 4.9 MB/s eta 0:00:01
   ------------------------------ --------- 13.3/17.7 MB 4.9 MB/s eta 0:00:01
   ------------------------------ --------- 13.4/17.7 MB 4.8 MB/s eta 0:00:01
   ------------------------------ --------- 13.5/17.7 MB 4.8 MB/s eta 0:00:01
   ------------------------------- -------- 13.7/17.7 MB 4.7 MB/s eta 0:00:01
   ------------------------------- -------- 13.8/17.7 MB 4.7 MB/s eta 0:00:01
   ------------------------------- -------- 13.9/17.7 MB 4.6 MB/s eta 0:00:01
   ------------------------------- -------- 14.0/17.7 MB 4.6 MB/s eta 0:00:01
   ------------------------------- -------- 14.1/17.7 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 14.2/17.7 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 14.4/17.7 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 14.5/17.7 MB 4.4 MB/s eta 0:00:01
   --------------------------------- ------ 14.7/17.7 MB 4.4 MB/s eta 0:00:01
   --------------------------------- ------ 14.7/17.7 MB 4.4 MB/s eta 0:00:01
   --------------------------------- ------ 14.8/17.7 MB 4.3 MB/s eta 0:00:01
   --------------------------------- ------ 14.9/17.7 MB 4.3 MB/s eta 0:00:01
   --------------------------------- ------ 15.0/17.7 MB 4.2 MB/s eta 0:00:01
   ---------------------------------- ----- 15.2/17.7 MB 4.2 MB/s eta 0:00:01
   ---------------------------------- ----- 15.2/17.7 MB 4.1 MB/s eta 0:00:01
   ---------------------------------- ----- 15.3/17.7 MB 4.1 MB/s eta 0:00:01
   ---------------------------------- ----- 15.4/17.7 MB 4.0 MB/s eta 0:00:01
   ----------------------------------- ---- 15.6/17.7 MB 4.0 MB/s eta 0:00:01
   ----------------------------------- ---- 15.8/17.7 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 16.0/17.7 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 16.1/17.7 MB 4.0 MB/s eta 0:00:01
   ------------------------------------ --- 16.2/17.7 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 16.4/17.7 MB 3.9 MB/s eta 0:00:01
   ------------------------------------- -- 16.5/17.7 MB 3.8 MB/s eta 0:00:01
   ------------------------------------- -- 16.6/17.7 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 16.8/17.7 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 16.9/17.7 MB 3.8 MB/s eta 0:00:01
   -------------------------------------- - 17.0/17.7 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 17.1/17.7 MB 3.7 MB/s eta 0:00:01
   -------------------------------------- - 17.2/17.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  17.3/17.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  17.5/17.7 MB 3.6 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------  17.7/17.7 MB 3.5 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 3.5 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0

[notice] A new release of pip is available: 24.0 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [12]:
!pip install mysql.connector

'pip' is not recognized as an internal or external command,
operable program or batch file.

In [14]:
import mysql.connector

In [16]:
conn = mysql.connector.connect(host='localhost',user='root',password='',database='world')

In [17]:
df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

C:\Users\HP\AppData\Local\Temp\ipykernel_21592\4272969784.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM countrylanguage",conn)

In [18]:
df

    CountryCode    Language IsOfficial  Percentage
0           ABW       Dutch          T         5.3
1           ABW     English          F         9.5
2           ABW  Papiamento          F        76.7
3           ABW     Spanish          F         7.4
4           AFG     Balochi          F         0.9
..          ...         ...        ...         ...
979         ZMB      Tongan          F        11.0
980         ZWE     English          T         2.2
981         ZWE     Ndebele          F        16.2
982         ZWE      Nyanja          F         2.2
983         ZWE       Shona          F        72.1

[984 rows x 4 columns]

In [19]:
pd.read_sql_query("SELECT * FROM city", conn)

C:\Users\HP\AppData\Local\Temp\ipykernel_21592\1432342221.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city", conn)

        ID            Name CountryCode       District  Population
0        1           Kabul         AFG          Kabol     1780000
1        2        Qandahar         AFG       Qandahar      237500
2        3           Herat         AFG          Herat      186800
3        4  Mazar-e-Sharif         AFG          Balkh      127800
4        5       Amsterdam         NLD  Noord-Holland      731200
...    ...             ...         ...            ...         ...
4074  4075      Khan Yunis         PSE     Khan Yunis      123175
4075  4076          Hebron         PSE         Hebron      119401
4076  4077        Jabaliya         PSE     North Gaza      113901
4077  4078          Nablus         PSE         Nablus      100231
4078  4079           Rafah         PSE          Rafah       92020

[4079 rows x 5 columns]